---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-ambassador.fullname" . }}
data:
  config.yaml: |-
    ---
    server:
      http:
        listen: "0.0.0.0:18080"
      grpc:
        listen: "0.0.0.0:19094"
      monitoring:
        listen: "0.0.0.0:28080"
    producer:
      resend:
        period: 1m
        rate_limit: 10000
      wal:
        mode: "fallback"
        path: /data/wal
        disable_topics:
         - test
        always_topics:
         - test1
    kafka:
        brokers:
            - "kafka-prod-us-or-01-01.prod.afdata.io:19093"
            - "kafka-prod-us-or-01-02.prod.afdata.io:19093"
            - "kafka-prod-us-or-01-03.prod.afdata.io:19093"
            - "kafka-prod-us-or-01-04.prod.afdata.io:19093"
            - "kafka-prod-us-or-01-05.prod.afdata.io:19093"
            - "kafka-prod-us-or-01-06.prod.afdata.io:19093"
            - "kafka-prod-us-or-01-07.prod.afdata.io:19093"
        # possible configuration parameters are:
        # https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
        "compression.codec": "gzip"
        "batch.num.messages": 2000
        "linger.ms": 3000
        "max.in.flight.requests.per.connection": 20
        "message.timeout.ms": 300000
        "socket.timeout.ms": 60000
        "statistics.interval.ms": 30000
        "security.protocol": "ssl"
        "ssl.ca.location": "/vault/secrets/kafka-pki/ca.crt"
        "ssl.certificate.location": "/vault/secrets/kafka-pki/kafka-client.crt"
        "ssl.key.location": "/vault/secrets/kafka-pki/kafka-client.key"
