apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-ambassador.fullname" . }}
  labels:
    {{- include "kafka-ambassador.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 18080
      targetPort: http-port
      protocol: TCP
      name: http-port
    - port: 19094
      targetPort: grpc-port
      protocol: TCP
      name: grpc-port
    - port: 28080
      targetPort: exporter-port
      protocol: TCP
      name: exporter-port
  selector:
    {{- include "kafka-ambassador.selectorLabels" . | nindent 4 }}
