{{- if .Values.serviceMonitor.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kafka-ambassador.fullname" . }}
  labels:
    {{- include "kafka-ambassador.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: exporter-port
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "kafka-ambassador.name" . }}
{{- end }}
