server:
  # http:
  #   listen: "0.0.0.0:18080"
  grpc:
    listen: "0.0.0.0:18282"
  monitoring:
    listen: "0.0.0.0:28080"
producer:
  max_in_transit: 1000
  cb:
    fails: 5
    timeout: 30
    requests: 5
  resend:
    period: 1m
    rate_limit: 100
  wal:
    mode: "fallback"
    path: /tmp/wal
    skip_topics:
      - test1
kafka:
  brokers:
    - "127.0.0.1:9092"
  # possible configuration parameters are:
  # https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
  "compression.codec": "gzip"
  "batch.num.messages": 100000
  "max.in.flight.requests.per.connection": 20
  "message.timeout.ms": 60000
  "socket.timeout.ms": 10000
