---
server:
  http:
    listen: "0.0.0.0:18080"
  grpc:
    listen: "0.0.0.0:18282"
  monitoring:
    listen: "0.0.0.0:28080"
kafka:
    brokers:
        - "127.0.0.1:9092"
    # possible configuration parameters are:
    # https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
    "compression.codec": "gzip"
    "batch.num.messages": 100000
    "max.in.flight.requests.per.connection": 20
